const BASE_COLORS = {
	COLOR_1: '#f8b195',
	COLOR_2: '#f67280',
	COLOR_3: '#c06c84',
	COLOR_4: '#6c5b7b',
	COLOR_5: '#355c7d'
}

export const COLORS = {
	MAIN_COLOR: BASE_COLORS.COLOR_2,
	APP_BACKGROUND_COLOR: BASE_COLORS.COLOR_2,
	MAP_MARKER_COLOR: BASE_COLORS.COLOR_3,
	BUTTON_COLOR: BASE_COLORS.COLOR_4,
	SECONDARY_ACTION_COLOR: `${BASE_COLORS.COLOR_4}90`,
	PRIMARY_TEXT_COLOR: '#fff',
	MARKER_MODAL_BACKGROUND: BASE_COLORS.COLOR_3
}