export const CONSTANTS = {
	MAP_VIEW_ANIMATION_DURATION: 500,
	MAP_ANIMATION_SIZE_DURATION: 750,
	MAP_MARKER_ANIMATION: 450,
	MARKER_CIRCLE_SIZE: 100,
	MARKER_MODAL_DURATION: 450,
	MARKER_CIRCLE_PADDING: 10,
	MARKER_TRIANGLE_WIDTH: 20,
	MARKER_TRIANGLE_HEIGHT: 40
}